### ISSUE TITLE
Does not seem to work on OSX

### ISSUE THREAD

**Issue by emanuelez** [boyski/audited-objects#9]
I was able to run the ao client properly on Linux.
It does not seem to work on OSX:

```
ao -o - run uname
Darwin
```

I used the version available on sourceforge.

I tried building from source from this repository with the same result.

**Comment by boyski** [comment]
I assume/hope you mean you used the version from github, not sourceforge?
Your email comes via github.

It works ok on OSX for me:

% ao -o- run uname
Darwin
64684,0,64677,oe4oz1.a7x1rc,9,xxxxxxx.com
,,,uname,.,-,7322df0e037897fe385344e622519598deb31c2e+5,-,uname
X,init,0.0,64684,0,64677,0,-,7322df0e037897fe385344e622519598deb31c2e+5,f,?,nbnohq.0,14352,pnx,,,/usr/bin/uname

David

**Comment by emanuelez** [comment]
I only found a prebuilt version of AO on Sourceforge and it seems to be pretty outdated. I didn't find any prebuild binaries on Github. I tried to build the Github repo with:

```
cd src
make -f GNUmakefile all
```

It compiles once I remove `-Werror` from the makefile since otherwise the build fails with:

```
In file included from unix.c:39:
./Interposer/libinterposer.h:334:1: warning: all paths through this function will call itself [-Winfinite-recursion]
```

**Comment by boyski** [comment]
To start with, "-f GNUmakefile all" are all defaults so "make" is just as
good.

This problem seems to come from more aggressive error checking in a recent
clang update causing it to find something that isn't really an error. I
made a minor change to obfuscate it further so clang will stop complaining
and it builds fine for me now.

**Comment by emanuelez** [comment]
Thanks! That solved the compilation issue: now I can build straight from `master`.
Still, the issue remains:

```
$ ao -o- run uname
Darwin
```

How can I help to diagnose the issue?

**Comment by boyski** [comment]
Apparently in El Capitan Apple added a "feature" called System Integrity
Protection or SIP which was intended to make things harder for malware but
makes things harder for the good guys too. One of the things SIP does is
prevent insertion of shared libraries into "system" programs meaning
utilities in places like /usr/bin. Notice in the sequence below how the
same program cannot be audited in /usr/bin but can when copied out.

% ao -o- run /usr/bin/uname
Darwin
% cp /usr/bin/uname ~
% ao -o- run ~/uname
Darwin
14481,0,14476,oe719m.bdgqo,8,xxxxxx.local,,,uname,.,-,886aa2afaf3c636471d885583a6a11d700ab059d+19,886aa2afaf3c636471d885583a6a11d700ab059d-1,/Users/xxxxx/uname
X,init,0.0,14481,0,14476,0,-,886aa2afaf3c636471d885583a6a11d700ab059d+19,f,?,oe719k.0,18320,pnx,8a1c860dd6b12964c2f24a44ca73dfc42e8b04ec,,uname

You can research SIP as well as I can but from a short look around it
appears it can be turned off via "csrutil disable". If you find another way
around this restriction please let me know.

David

**Comment by emanuelez** [comment]
Thank you for investigating on this! I will now close the issue 👍 
This should probably be documented somewhere on the website :)
